apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-ingress
  labels:
    app: inventory
spec:
  rules:
  - host: cluster-registry
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: inventory
            port:
              number: 8080