apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  labels:
    app: postgres
type: Opaque
data:
  database_uri: cG9zdGdyZXNxbCtwc3ljb3BnOi8vcG9zdGdyZXM6cGdzM2NyM3RAcG9zdGdyZXM6NTQzMi9pbnZlbnRvcnk=
  password: cGdzM2NyM3Q=