name: CI Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.11.12-bullseye

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install -U pip pipenv
          pipenv install --system --dev

      - name: Lint with flake8
        run: flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Lint with pylint
        run: pylint service tests --max-line-length=127

      - name: Run unit tests
        env:
          DATABASE_URI: "postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/postgres"
        run: pytest --pspec --cov=service --cov-fail-under=95 --cov-report=xml

      ######################################################################
      # Create a CODECOV_TOKEN in Settings->Secrets and variables->Actions
      # and then uncomment the CodeCov action during hands-on lab
      ######################################################################

      - name: Install packages for Codecov to work
        run: apt-get update && apt-get install -y git curl gpg

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CSCI-GA-2820-FA25-001/inventory

      - name: Install Chrome for BDD tests
        run: |
          apt-get update
          apt-get install -y chromium chromium-driver

      - name: Start Flask service in background
        env:
          DATABASE_URI: "postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/postgres"
        run: |
          gunicorn --bind 0.0.0.0:8080 --log-level=info wsgi:app &
          sleep 5
          curl http://localhost:8080/

      - name: Run BDD tests
        env:
          BASE_URL: "http://localhost:8080"
        run: behave
